### ISSUE TITLE
Cannot start app-inspector: package com.macaca.android.testing is not exists

### ISSUE THREAD

**Issue by AviramNahon** [macacajs/app-inspector#215]
Hi Guys,
I don't seem to be able to run app-inspector.
it gives me error: "uiautomator-client.js:38:12 [master] pid:4332 Package com.macaca.android.testing is not exists" and "app-debug.apk not found, please resolve and reinstall android driver".
Can you please assist?
--------------------------------------
**Environment check**:
$ npm i macaca-cli -g && macaca doctor
Macaca was successfully installed!
  macaca-doctor version: 2.0.15
  Node.js checklist:
  node env: C:\Program Files\nodejs\node.exe
  node version: v8.12.0
  Android checklist:
  JAVA version is `1.8`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_201`
  ANDROID_HOME is set to `C:\Users\shimon\AppData\Local\Android\Sdk`
  Platforms is set to `C:\Users\shimon\AppData\Local\Android\Sdk\platforms\android-28`
  ADB tool is set to `C:\Users\shimon\AppData\Local\Android\Sdk\platform-tools\adb.exe`
  GRADLE_HOME is set to `C:\Gradle\gradle-5.1.1\bin`
  Installed driver list:

---

- app inspector version / 版本号:
2.0.22

- os version / 系统:
WIN10 pro

- device  information / 设备版本:
Samsung J6

- terminal log / 终端输出信息:

> try `app-inspector -u xxxx --verbose` for more log detail.
>> server.js:16:12 [master] pid:5324 server start with config:
 { port: 5678,
  verbose: true,
  udid: '5200414eea6165b3',
  ip: '172.29.116.177',
  host: 'DESKTOP-LO5JI1F',
  loaded_time: '2019-01-23 01:48:12' }
>> app-inspector.js:45:12 [master] pid:5324 server start at: http://172.29.116.177:5678
>> uiautomator-client.js:38:12 [master] pid:5324 Package com.macaca.android.testing is not exists，execute intsall action.
>> uiautomator-client.js:42:14 [master] pid:5324 C:\Users\shimon\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk not found, please resolve and reinstall android driver
Error: >> uiautomator-client.js:42:14 [master] pid:5324 C:\Users\shimon\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk not found, please resolve and reinstall android driver
    at Logger.error (C:\Users\shimon\AppData\Roaming\npm\node_modules\app-inspector\node_modules\xlogger\lib\xlogger.js:169:9)
    at UIAutomator.init (C:\Users\shimon\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\lib\uiautomator-client.js:42:14)
    at UIAutomator.init.throw (<anonymous>)
    at onRejected (C:\Users\shimon\AppData\Roaming\npm\node_modules\app-inspector\node_modules\co\index.js:81:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by AviramNahon** [comment]
I have also tried to run as suggested in another issue:
$ cd ...npm\node_modules\app-inspector\node_modules\uiautomatorwd
$ node ./scripts/build.js
and got this:

(node:6868) **UnhandledPromiseRejectionWarning: ,Starting a Gradle Daemon** (subsequent builds will be faster)

> Configure project :app
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to ...l\Android\Sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

File C:\Users\shimon\.android\repositories.cfg could not be loaded.
Checking the license for package Android SDK Build-Tools 25.0.2 in ...\Android\Sdk\licenses
Warning: License for package Android SDK Build-Tools 25.0.2 not accepted.
Checking the license for package Android SDK Platform 26 in ...\Android\Sdk\licenses
Warning: License for package Android SDK Platform 26 not accepted.
,
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 25.0.2, Android SDK Platform 26].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 43s

(node:6868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by paradite** [comment]
You need to accept the licenses as stated in the error. Refer to the docs on how to setup Android environment: https://macacajs.github.io/guide/environment-setup.html#android

Then `npm uninstall -g app-inspector` and `npm i -g app-inspector`

**Comment by AviramNahon** [comment]
Thanks,
the problem was not the licenses (I already accepted all before).
the problem was that I probably missed installing *macaca-android* before installing app-inspector.
Now the server is up without error but the view source is empty... gives only: <unknown_class></unknown_class>.
I will open a new issue on that.

**Comment by clark-ewerton** [comment]
Just adding a quick comment here...

This error: **AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\apk\debug\app-debug.apk not found** 

means that is coming from that module "uiautomatorwd".

And that module only runs in JDK 8 nowadays because is deprecated. So if you wanna run macaca inspector these days, please make sure to switch java version to JDK 8 only to run the inspector ok?

I'm using Windows, so I created a .bat file with the following content to sort the issue out:

`@echo off
set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_202
set PATH=%JAVA_HOME%\bin;%PATH%
cd C:\Users\clark\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd
gradlew.bat assembleDebug `

If, by any chance, happens to throw this error:

> Task :app:packageDebug FAILED

**FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > com.android.ide.common.signing.KeytoolException: Failed to read key AndroidDebugKey from store "C:\Users\clark\.android\debug.keystore": Invalid keystore format**

You can run the following command to tackle it:

` del C:\Users\clark\.android\debug.keystore
keytool -genkeypair -alias androiddebugkey -keypass android -keystore C:\Users\clark\.android\debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 10000 -keyalg RSA -keysize 2048 -storetype JKS
keytool -list -v -keystore C:\Users\clark\.android\debug.keystore -storepass android `

And lastly it's gonna throw this error probably right away:

**>> uiautomator-client.js:61:14 [master] pid:7712 C:\Users\clark\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\apk\
androidTest\debug\app-debug-androidTest.apk not found, please resolve and reinstall android driver**

Resolve it by running the script:
`
@echo off
set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_202
set PATH=%JAVA_HOME%\bin;%PATH%
cd C:\Users\clark\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd
gradlew.bat assembleAndroidTest`
